# Simple GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Administrative Law Guide
description: A comprehensive interactive guide to understanding administrative law
baseurl: ""  # Using empty baseurl for simpler paths

# File inclusions - keep it simple
include: 
  - "AdminLawGuide/**"
