theme: jekyll-theme-minimal
title: Administrative Law Guide
description: A comprehensive interactive guide to understanding administrative law
include: 
  - "*.html"
  - "*.js"
  - "*.css"
  - "/AdminLawGuide/**/*"
# Redirect all requests to main index.html
plugins:
  - jekyll-redirect-from
