theme: jekyll-theme-minimal
title: Administrative Law Guide
description: A comprehensive interactive guide to understanding administrative law
baseurl: "/AdminLawGuide"
url: ""
include: 
  - "*.html"
  - "*.js"
  - "*.css"
  - "assets/**/*"
plugins:
  - jekyll-redirect-from

# Add these settings for proper asset URL handling
sass:
  style: compressed
  
# Define site-wide variables for asset paths
defaults:
  - scope:
      path: ""
    values:
      image_path: "/AdminLawGuide/assets"
