# AdminLawGuide Jekyll Configuration
theme: jekyll-theme-minimal
title: Administrative Law Guide
description: A comprehensive interactive guide to understanding administrative law
baseurl: "/AdminLawProject"  # Must match repository name
url: "https://amycozy.github.io"  
include: 
  - "*.html"
  - "*.js"
  - "*.css"
  - "assets/**/*"
plugins:
  - jekyll-redirect-from

# Asset handling
sass:
  style: compressed
  
# Define site-wide variables for asset paths
defaults:
  - scope:
      path: ""
    values:
      image_path: "/AdminLawProject/AdminLawGuide/assets"
